/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as ProgrammeRouteImport } from './routes/programme'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CandidatureSpeakerRouteImport } from './routes/candidature-speaker'
import { Route as AmbassadeurRouteImport } from './routes/ambassadeur'
import { Route as IndexRouteImport } from './routes/index'

const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeRoute = ProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatureSpeakerRoute = CandidatureSpeakerRouteImport.update({
  id: '/candidature-speaker',
  path: '/candidature-speaker',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadeurRoute = AmbassadeurRouteImport.update({
  id: '/ambassadeur',
  path: '/ambassadeur',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambassadeur': typeof AmbassadeurRoute
  '/candidature-speaker': typeof CandidatureSpeakerRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/inscription': typeof InscriptionRoute
  '/partenaires': typeof PartenairesRoute
  '/programme': typeof ProgrammeRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambassadeur': typeof AmbassadeurRoute
  '/candidature-speaker': typeof CandidatureSpeakerRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/inscription': typeof InscriptionRoute
  '/partenaires': typeof PartenairesRoute
  '/programme': typeof ProgrammeRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambassadeur': typeof AmbassadeurRoute
  '/candidature-speaker': typeof CandidatureSpeakerRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/inscription': typeof InscriptionRoute
  '/partenaires': typeof PartenairesRoute
  '/programme': typeof ProgrammeRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambassadeur'
    | '/candidature-speaker'
    | '/contact'
    | '/faq'
    | '/inscription'
    | '/partenaires'
    | '/programme'
    | '/speakers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambassadeur'
    | '/candidature-speaker'
    | '/contact'
    | '/faq'
    | '/inscription'
    | '/partenaires'
    | '/programme'
    | '/speakers'
  id:
    | '__root__'
    | '/'
    | '/ambassadeur'
    | '/candidature-speaker'
    | '/contact'
    | '/faq'
    | '/inscription'
    | '/partenaires'
    | '/programme'
    | '/speakers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbassadeurRoute: typeof AmbassadeurRoute
  CandidatureSpeakerRoute: typeof CandidatureSpeakerRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  InscriptionRoute: typeof InscriptionRoute
  PartenairesRoute: typeof PartenairesRoute
  ProgrammeRoute: typeof ProgrammeRoute
  SpeakersRoute: typeof SpeakersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme': {
      id: '/programme'
      path: '/programme'
      fullPath: '/programme'
      preLoaderRoute: typeof ProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidature-speaker': {
      id: '/candidature-speaker'
      path: '/candidature-speaker'
      fullPath: '/candidature-speaker'
      preLoaderRoute: typeof CandidatureSpeakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassadeur': {
      id: '/ambassadeur'
      path: '/ambassadeur'
      fullPath: '/ambassadeur'
      preLoaderRoute: typeof AmbassadeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbassadeurRoute: AmbassadeurRoute,
  CandidatureSpeakerRoute: CandidatureSpeakerRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  InscriptionRoute: InscriptionRoute,
  PartenairesRoute: PartenairesRoute,
  ProgrammeRoute: ProgrammeRoute,
  SpeakersRoute: SpeakersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
